name: 'build-test'

on: 
  pull_request:
  push:
    branches:
      - '**'

jobs:
  plugin-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7.0.1

    - name: Run plugin check
      uses: wordpress/plugin-check-action@v1.1.7
      with:
        exclude-files: |
          .gitignore
          .gitattributes
          .wp-env.json
          .distignore
          CHANGELOG.md
          CODE_OF_CONDUCT.md
          CONTRIBUTING.md
          README.md
          SECURITY.md
        exclude-directories: |
          .github